
POST {{$dotenv PROVIDER_NODE_OGMIOS_URL}}/ HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "method": "queryNetwork/blockHeight",
  "id": "{{$dotenv OGMIOS_REQ_ID}}"
}