
PUT  {{$dotenv PROVIDER_NODE_KUPO_URL}}/patterns/{{$dotenv CARDANO_VESTING_ADDRESS}} HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "rollback_to": {
    "slot_no": 55814394,
    "header_hash": "bdd4baa2c81d0500a695f836332193ea06c2ce364e585057142220fc0782144c"
  },
  "limit": "unsafe_allow_beyond_safe_zone"
}