
POST {{$dotenv PROVIDER_NODE_OGMIOS_URL}}/ HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "method": "queryLedgerState/utxo",
  "params": {
    "outputReferences": [
      {
        "transaction": {
          "id": "{{$dotenv OGMIOS_TX_HASH}}"
        },
        "index": 43
      }
    ]
  },
  "id": "{{$dotenv OGMIOS_REQ_ID}}"
}