import addressParamHandlerUnbound from './addressParamHandler.unbound';
import addEntityInToRequestImplicits from 'web/serverModules/common/paramHandlers/addEntityInToRequestImplicits/addEntityInToRequestImplicits';

export default addressParamHandlerUnbound(addEntityInToRequestImplicits);
