version: "3"
services:
  server:
    image: cardano/server
    container_name: server
    build:
      context: ./
    networks:
      - cardano-network
    volumes:
      - ./storage:/home/node/app/storage
    env_file:
      - .env
    ports:
      - "8100:8000"
      - "8101:8001"

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    networks:
      - cardano-network
    ports:
      - "8102:8080"
    environment:
      - KEYCLOAK_USER
      - KEYCLOAK_PASSWORD
      - KEYCLOAK_IMPORT=/tmp/realm-demo.json
    volumes:
      - ./dockers/sso/realm-demo.json:/tmp/realm-demo.json

  swagger-ui:
    image: shotat/swagger-ui-watcher
    container_name: swagger-ui
    networks:
      - cardano-network
    ports:
      - "8103:8000"
    volumes:
      - ./docs:/docs
    command: ["/docs/api/index.yaml"]

  kupo-init-scan:
    image: cardanosolutions/kupo:latest
    profiles:
      - init
    container_name: kupo-init-scan
    networks:
      - cardano-network
    volumes:
      - ./storage/kupo_db:/db
    command: [
      "--ogmios-host", "${REMOTE_NODE_HOST}",
      "--ogmios-port", "1337",
      "--since", "${KUPO_SINCE}",
      "--match", "${CARDANO_GIFT_ADDRESS}",
      "--match", "${CARDANO_WALLET_ADDRES_1}",
      "--match", "${CARDANO_WALLET_ADDRES_2}",
      "--workdir", "/db",
      "--defer-db-indexes"
    ]

  kupo:
    image: cardanosolutions/kupo:latest
    container_name: kupo
    networks:
      - cardano-network
    ports:
      - "8104:1442"
    volumes:
      - ./storage/kupo_db:/db
    command: [
      "--host", "0.0.0.0",
      "--port", "1442",
      "--ogmios-host", "${REMOTE_NODE_HOST}",
      "--ogmios-port", "1337",
      "--since", "${KUPO_SINCE}",
      "--match", "${CARDANO_GIFT_ADDRESS}",
      "--match", "${CARDANO_WALLET_ADDRES_1}",
      "--match", "${CARDANO_WALLET_ADDRES_2}",
      "--workdir", "/db"
    ]

  splunk:
    image: demo/splunk
    container_name: splunk
    build:
      context: ./dockers/splunk
      args:
        - SPLUNK_PASSWORD
        - LOG_SPLUNK_TOKEN
    networks:
      - cardano-network
    ports:
      - "8105:8102"
      - "8088:8088"
    volumes:
      - splunk-var:/opt/splunk/var
      - splunk-etc:/opt/splunk/etc

networks:
  cardano-network:
    driver: bridge
    attachable: true

volumes:
  splunk-var:
  splunk-etc:
